name = 'kulmajaba'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = ''

# The home page of the theme, where the source can be found
homepage = ''

# If you have a running demo of the theme
demosite = ''

# Taxonomy terms
tags = []
features = []

# If the theme has a single author
[author]
  name = ''
  homepage = ''

