name: Deploy UI to dev

on:
  # push:
    # branches: [ "develop" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    uses: kulmajaba/kulmajaba-homepage/.github/workflows/deploy.yml@develop
    with:
      deploy-path: 'sites/kulmajaba-homepage-dev'
      base-url: 'https://dev.kulmajaba.com'
      build-flags: '-DEF'
    secrets: inherit